version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule: {interval: weekly, day: monday, time: "08:40", timezone: America/Toronto}
    open-pull-requests-limit: 5
    allow:
      - dependency-name: "*"
        update-types: [version-update:semver-minor, version-update:semver-patch]
    groups:
      rust-routine-updates: {applies-to: version-updates, patterns: ["*"], update-types: [minor, patch]}
      rust-security-updates: {applies-to: security-updates, patterns: ["*"]}

  - package-ecosystem: github-actions
    directory: /
    schedule: {interval: weekly, day: monday, time: "08:50", timezone: America/Toronto}
    open-pull-requests-limit: 5
    allow:
      - dependency-name: "*"
        update-types: [version-update:semver-minor, version-update:semver-patch]
    groups:
      action-routine-updates: {applies-to: version-updates, patterns: ["*"], update-types: [minor, patch]}
      action-security-updates: {applies-to: security-updates, patterns: ["*"]}
